server:
  port: 8080

spring:
  application:
    name: music-store-graphql

  # Configuración H2
  datasource:
    url: jdbc:h2:mem:musicstore
    driverClassName: org.h2.Driver
    username: santinuin
    password: password

  # Configuración JPA
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # Consola H2 habilitada
  h2:
    console:
      enabled: true
      path: /h2-console

  # Configuración GraphQL
  graphql:
    graphiql:
      enabled: true
      path: /graphiql
    path: /graphql
    cors:
      allowed-origins: "*"
      allowed-methods: "*"

# Logging
logging:
  level:
    com.ejemplo.musicstore: DEBUG
    org.springframework.graphql: DEBUG